<?xml version="1.0" ?>
<robot name="omniturtle" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find omniturtle_description)/urdf/common_properties.xacro"/>
  <xacro:include filename="$(find omniturtle_description)/urdf/omniturtle.gazebo.xacro"/>
  <xacro:include filename="$(find omniturtle_description)/urdf/mecanum_description.urdf.xacro"/>
  <xacro:include filename="$(find omniturtle_description)/urdf/mecanum_description.gazebo.xacro"/>

  <!-- Properties block -->
  <xacro:property name="PI" value="3.1415926535897931"/>

  <xacro:property name="b_diam" value="0.13755" />    <!-- base diameter -->
  <xacro:property name="b_height" value="0.14413" />  <!-- base height -->

  <!--Mecanum wheel propertires-->
  <xacro:property name="mw_m" value="0.1"/>   <!-- mecanum's mass -->
  <xacro:property name="mw_d" value="0.034"/> <!-- mecanum's diameter (whole) -->
  <xacro:property name="mw_w" value="0.012"/> <!-- mecanum's width -->
  <xacro:property name="r_num" value="8"/>    <!-- rollers number -->
  <xacro:property name="c_c" value="0.9"/>    <!-- coverage coefficient -->
  <xacro:property name="r_d" value="0.0095"/> <!-- roller's diameter -->
  <xacro:property name="r_w" value="0.005"/>  <!-- roller's width -->

  <!-- Links & Joints block -->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 0.010" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0.0 0 0.0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://omniturtle_description/meshes/bases/burger_base_clear.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="light_black"/>
    </visual>

    <collision>
      <origin xyz="0.0 0.0 ${b_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="0.140 0.140 0.143"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.82573504"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0"
               iyy="1.0" iyz="0.0"
               izz="1.0" />
    </inertial>
  </link>

  <xacro:mecanum_wheel1 base_name="base_link" base_diam="b_diam" suffix="rf" right="1"   front="1"/>
  <xacro:mecanum_wheel2 base_name="base_link" base_diam="b_diam" suffix="lf" right="-1"   front="1"/>
  <xacro:mecanum_wheel2 base_name="base_link" base_diam="b_diam" suffix="rb" right="1"   front="-1"/>
  <xacro:mecanum_wheel1 base_name="base_link" base_diam="b_diam" suffix="lb" right="-1"   front="-1"/>

  <!-- Transmission macro -->
  <xacro:macro name="transmiss" params="suffix">
    <!-- Wheel transmission -->
    <transmission name="wheel_${suffix}_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="wheel_${suffix}_joint">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="wheel_${suffix}_motor">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

  </xacro:macro>

  <!-- Add transmissions -->
  <!-- xacro:transmiss suffix="rf"/ -->
  <!-- xacro:transmiss suffix="lf"/ -->  
  <!-- xacro:transmiss suffix="rb"/ -->  
  <!-- xacro:transmiss suffix="lb"/ -->  


  <!-- Sensors block -->
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="-0.032 0 0.068" rpy="0 0 0"/>
  </joint>

  <link name="imu_link"/>

  <joint name="scan_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_scan"/>
    <origin xyz="-0.032 0 0.172" rpy="0 0 0"/>
  </joint>

  <link name="base_scan">
    <visual>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/sensors/lds.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0.015 0 -0.0065" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.0315" radius="0.055"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

</robot>
