omniturtle:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  # Wheels
  wheel_rf_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_rf_joint
    pid: {p: 1.0, i: 0.01, d: 0.1}

  wheel_lf_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_lf_joint
    pid: {p: 1.0, i: 0.01, d: 0.1}

  wheel_rb_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_rb_joint
    pid: {p: 1.0, i: 0.01, d: 0.1}

  wheel_lb_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_lb_joint
    pid: {p: 1.0, i: 0.01, d: 0.1}




