omniturtle:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  # Wheels
  mecanum_rf_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: mecanum_rf_joint
    pid: {p: 1.0, i: 0.001, d: 0.5}

  mecanum_lf_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: mecanum_lf_joint
    pid: {p: 1.0, i: 0.001, d: 0.5}

  mecanum_rb_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: mecanum_rb_joint
    pid: {p: 1.0, i: 0.001, d: 0.5}

  mecanum_lb_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: mecanum_lb_joint
    pid: {p: 1.0, i: 0.001, d: 0.5}




